import type { ConversationFile, ConversationMeta } from '../types'
import { apiLatencyDashboard } from './api-latency-dashboard'
import { churnCohortAnalysis } from './churn-cohort-analysis'
import { cloudflareBillAnomaly } from './cloudflare-bill-anomaly'
import { demoVideoToGif } from './demo-video-to-gif'
import { dependencySweep } from './dependency-sweep'
import { designSystemAudit } from './design-system-audit'
import { docsArabicTranslation } from './docs-arabic-translation'
import { githubActionsMigration } from './github-actions-migration'
import { incidentPostmortem } from './incident-postmortem'
import { mobileCrashTriage } from './mobile-crash-triage'
import { outboxReplayBugfix } from './outbox-replay-bugfix'
import { q3OkrProgress } from './q3-okr-progress'
import { q4InfraCostForecast } from './q4-infra-cost-forecast'
import { releaseNotes214 } from './release-notes-2-14'
import { slowQueryAudit } from './slow-query-audit'
import { sprintVelocity } from './sprint-velocity'
import { takeHomeReview } from './take-home-review'
import { testFlakinessReport } from './test-flakiness-report'
import { voiceMemoActionItems } from './voice-memo-action-items'
import { weeklyEngineeringDigest } from './weekly-engineering-digest'

/**
 * Every demo conversation, newest first. Each module builds one with the DSL
 * in ./dsl.ts; this file is generated by the integrator's wire script —
 * adding a conversation is one module plus a rerun.
 */
export const CONVERSATIONS: ConversationFile[] = [
  apiLatencyDashboard,
  churnCohortAnalysis,
  cloudflareBillAnomaly,
  demoVideoToGif,
  dependencySweep,
  designSystemAudit,
  docsArabicTranslation,
  githubActionsMigration,
  incidentPostmortem,
  mobileCrashTriage,
  outboxReplayBugfix,
  q3OkrProgress,
  q4InfraCostForecast,
  releaseNotes214,
  slowQueryAudit,
  sprintVelocity,
  takeHomeReview,
  testFlakinessReport,
  voiceMemoActionItems,
  weeklyEngineeringDigest
].sort((a, b) => b.updatedAt - a.updatedAt)

export const CONVERSATION_BY_ID: ReadonlyMap<string, ConversationFile> = new Map(
  CONVERSATIONS.map((c) => [c.id, c])
)

export function conversationMetas(): ConversationMeta[] {
  return CONVERSATIONS.map((c) => ({
    id: c.id,
    title: c.title,
    updatedAt: c.updatedAt,
    channel: c.channel,
    ...(c.projectId ? { projectId: c.projectId } : {}),
    ...(c.icon ? { icon: c.icon } : {}),
    messageCount: c.messages.length
  }))
}

/** Every workspace path any conversation references (attachments and deliveries). */
export function conversationFilePaths(): string[] {
  const out = new Set<string>()
  for (const c of CONVERSATIONS) {
    for (const p of Object.keys(c.files ?? {})) out.add(p)
    for (const m of c.messages) {
      for (const a of m.attachments ?? []) out.add(a.filePath)
      for (const s of m.segments ?? []) {
        if (s.kind === 'tool_result') {
          for (const match of s.output.matchAll(
            /\[wolffish-output:\s*([^\]\n]+?)\s+\((?:image|audio|video|document|file|chart)\)\]/g
          )) {
            out.add(match[1].trim())
          }
        }
      }
    }
  }
  return [...out]
}
